// Rerender miis slowly in background
// This is used when we change how rendering works to make sure all miis are consistent.
// We manually run DB queries to find miis that need to be rerendered, then add their IDs into the rerender database collection.

import "./setEnvs.js";
import crypto from "node:crypto";
import fs from "fs";
import {
    renderStoredMiiImageResult,
    withMiiImagePublishLock,
    writeMiiImageBuffer
} from "./miiImageRenderer.js";
import { getConfiguredLtdRendererRevision, LtdRenderError } from "./ltdImageRenderer.js";
import {
    LTD_RENDER_BACKGROUND_MODE,
    LTD_RENDER_RASTER_PROFILE,
    persistLtdRenderPortraitStateCas,
    publishCasGuardedLtdImage
} from "./ltdImageCachePolicy.js";
import { getMiiAssetPaths } from "./miiAssets.js";
import { connectionPromise, Miis, RerenderQueue } from "./database.js";
import { sendWebhookPayload } from "./monitoring.js";
import { resolveMiiRendererRoute } from "./miiRendererRouting.js";


const rerenderInterval = 5000;
const idleRerenderInterval = 60000;
async function isCached(filePath) {
    return fs.promises.access(filePath, fs.constants.F_OK).then(() => true).catch(() => false);
}

async function rerenderNext() {
    const rendererRevision = getConfiguredLtdRendererRevision();
    const next = await RerenderQueue.findOne({
        intent: "ltd",
        rendererRevision
    }).sort({ addedAt: 1 });
    if (!next) return false;

    const { miiId } = next;

    const miiDoc = await Miis.findOne({ id: miiId }).select("+ltdData");
    if (!miiDoc) {
        await RerenderQueue.deleteOne({ miiId });
        return true;
    }

    const isPrivate = Boolean(miiDoc.private);
    const { imgPath } = getMiiAssetPaths(miiId, isPrivate);

    const hasImg = await isCached(imgPath);
    if (!hasImg) {
        await RerenderQueue.deleteOne({ miiId });
        return true;
    }

    const miiData = miiDoc.toObject();

    // This legacy queue is explicitly LTD-provenance/CAS scoped. Standard
    // TL/RFL images are generated by the era-aware site image boundary and
    // must never be published into ltdRender state.
    if (resolveMiiRendererRoute(miiData).backend !== "LTD") {
        console.log(`[rerender] Skipped non-LTD render ${miiId} from the LTD queue`);
        await RerenderQueue.deleteOne({ miiId });
        return true;
    }

    try {
        const rendered = await renderStoredMiiImageResult(miiData);
        const readyState = {
            status: "ready",
            ...rendered.provenance,
            renderedAt: new Date()
        };
        const updateState = async (observedMii, state) => await persistLtdRenderPortraitStateCas({
            mii: observedMii,
            state,
            updateOne: async (filter, update) => await Miis.updateOne(filter, update)
        });
        const committed = await publishCasGuardedLtdImage({
            readyState,
            publishToken: crypto.randomBytes(16).toString("hex"),
            withPublishLock: task => withMiiImagePublishLock(imgPath, task),
            resolveCurrentMii: async () => await Miis.findOne({ id: miiId })
                .select("+ltdData")
                .lean(),
            validateClaimedMii: async (claimedMii) =>
                resolveMiiRendererRoute(claimedMii).backend === "LTD",
            claimPublishing: async (_currentMii, publishingState) => rendered.authorizationMii
                ? await updateState(rendered.authorizationMii, publishingState)
                : false,
            publishAsset: async () => await writeMiiImageBuffer(rendered.buffer, imgPath),
            finalizeReady: updateState
        });
        if (!committed) throw new Error("The Mii changed while its queued LTD render was being published.");
    } catch (error) {
        if (!(error instanceof LtdRenderError) || !error.deterministic) throw error;
        const authorizationMii = error.authorizationMii;
        const failureRevision = String(error.rendererRevision || "").toLowerCase();
        if (
            authorizationMii
            && String(authorizationMii.ltdSha256 || "").toLowerCase()
                === String(error.ltdSha256 || "").toLowerCase()
            && failureRevision === rendererRevision.toLowerCase()
        ) {
            await persistLtdRenderPortraitStateCas({
                mii: authorizationMii,
                state: {
                    status: "unsupported",
                    ltdSha256: String(error.ltdSha256).toLowerCase(),
                    failureCode: error.code,
                    rendererRevision: failureRevision,
                    backgroundMode: LTD_RENDER_BACKGROUND_MODE,
                    presentationContextKind: error.presentationContextKind,
                    presentationContextSha256: error.presentationContextSha256,
                    rasterProfile: error.rasterProfile || LTD_RENDER_RASTER_PROFILE,
                    checkedAt: new Date()
                },
                updateOne: async (filter, update) => await Miis.updateOne(filter, update)
            });
        }
    }
    
    console.log(`[rerender] Processed LTD render for ${miiId}`);
    await RerenderQueue.deleteOne({ miiId });
    return true;
}

async function rerenderThread() {
    await connectionPromise; // might run this directly sometimes

    let foundLast = false;
    while (true) {
        try {
            foundLast = await rerenderNext();

            // Wait longer before querying if there wasn't anything there last time
            await new Promise(r => setTimeout(r, foundLast ? rerenderInterval : idleRerenderInterval));
        } catch (e) {
            // Report error, this shouldn't ever happen
            const err = `Rerenderer failed with error:\n\`\`\`${e.stack || e}\`\`\``;
            sendWebhookPayload({
                content: err.length > 4000 ? err.substring(0, 4000) : err
            }); 
    
            foundLast = false;
            await new Promise(r => setTimeout(r, idleRerenderInterval));
        }
    }
}

export function startRerenderer() {
    rerenderThread().catch(e => {
        const err = `Rerenderer failed with error:\n\`\`\`${e.stack || e}\`\`\``;
        sendWebhookPayload({
            content: err.length > 4000 ? err.substring(0, 4000) : err
        }); 
    });
}
